start: ident | ncall | closure | eexpr
call: (call | texpr) (" _ " texpr)* texpr texpr
ncall: (call | texpr) (" _ " texpr)* texpr eexpr
?eexpr: texpr | nexpr
?nexpr: "\\" (eexpr | ncall | ident | closure | partial)
?texpr: ident | "(" (ident | ncall | closure | partial) ")"
partial: texpr eexpr
closure: destruct "-> " (eexpr | call)
destruct: (IDENT | "(" destruct ")")+
ident: IDENT | SPECIAL
SPECIAL: /\|>|\./ 
IDENT: /(str\.)?[A-Za-z_0-9]+/

%import common.WS
%ignore WS